apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-meta
spec:
  selector:
    matchLabels:
      app: frontend-deployment-label
  template:
    metadata:
      labels:
        app: frontend-deployment-label
    spec:
      containers:
        - name: app
          image: raktim00/httpd-server
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
