
apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment-label
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 31201
  selector:
    app: frontend-deployment